#!/usr/bin/env bash
set -euo pipefail

WS="/Users/sawyer/.openclaw/workspace-openclaw-maintainer"
REPO="/Users/sawyer/github/forks/openclaw"
CLAUDE_MD="$WS/CLAUDE.md"
BOOTSTRAP_MD="$WS/BOOTSTRAP.md"
HOOK_DIR="$WS/hooks/git"
COMMIT_HOOK="$HOOK_DIR/commit-msg"
PREPUSH_HOOK="$HOOK_DIR/pre-push"
AUDIT_SCRIPT="$WS/scripts/agent-attribution-audit.sh"

has_text() {
  local pattern="$1" file="$2"
  LC_ALL=C grep -Eiq "$pattern" "$file"
}

triage=0
verification=0
attribution=0
notes=()

# --- TRIAGE QUALITY (10) ---
if has_text "Mandatory OpenClaw Preflight" "$CLAUDE_MD"; then triage=$((triage+2)); else notes+=("triage: missing Mandatory OpenClaw Preflight"); fi
if has_text "Triage & Duplicate-Avoidance Protocol" "$CLAUDE_MD"; then triage=$((triage+2)); else notes+=("triage: missing duplicate-avoidance protocol"); fi
if has_text "gh issue view" "$CLAUDE_MD"; then triage=$((triage+2)); else notes+=("triage: missing gh issue check"); fi
if has_text "gh pr list" "$CLAUDE_MD"; then triage=$((triage+2)); else notes+=("triage: missing gh pr duplicate check"); fi
if has_text "git log --oneline --grep" "$CLAUDE_MD"; then triage=$((triage+2)); else notes+=("triage: missing git log duplicate check"); fi

# --- VERIFICATION EVIDENCE (10) ---
if has_text "Never claim completion without verification evidence" "$CLAUDE_MD"; then verification=$((verification+2)); else notes+=("verification: missing non-negotiable evidence rule"); fi
if has_text "corepack pnpm build" "$CLAUDE_MD"; then verification=$((verification+2)); else notes+=("verification: missing build gate"); fi
if has_text "corepack pnpm check" "$CLAUDE_MD"; then verification=$((verification+2)); else notes+=("verification: missing check gate"); fi
if has_text "corepack pnpm test" "$CLAUDE_MD"; then verification=$((verification+2)); else notes+=("verification: missing test gate"); fi
if has_text "\*\*Decision\*\*" "$CLAUDE_MD" && has_text "\*\*Evidence\*\*" "$CLAUDE_MD" && has_text "\*\*Next move\*\*" "$CLAUDE_MD"; then verification=$((verification+2)); else notes+=("verification: missing handoff format"); fi

# --- ATTRIBUTION COMPLIANCE (10) ---
if [[ -x "$COMMIT_HOOK" ]]; then attribution=$((attribution+1)); else notes+=("attribution: commit-msg hook missing/not executable"); fi
if [[ -x "$PREPUSH_HOOK" ]]; then attribution=$((attribution+1)); else notes+=("attribution: pre-push hook missing/not executable"); fi
if [[ -x "$AUDIT_SCRIPT" ]]; then attribution=$((attribution+1)); else notes+=("attribution: audit script missing/not executable"); fi

# Hook path wired in repo
hook_path="$(git -C "$REPO" config --get core.hooksPath || true)"
if [[ "$hook_path" == "$HOOK_DIR" ]]; then
  attribution=$((attribution+2))
else
  notes+=("attribution: core.hooksPath not set to maintainer hook dir")
fi

# Synthetic commit message tests
tmp_ok="$(mktemp)"
tmp_bad="$(mktemp)"
printf 'fix(signal): harden reaction id resolution\n' > "$tmp_ok"
printf 'fix: generated by Claude\n\nCo-Authored-By: Bot <bot@example.com>\n' > "$tmp_bad"

if "$COMMIT_HOOK" "$tmp_ok" >/dev/null 2>&1; then attribution=$((attribution+2)); else notes+=("attribution: commit-msg hook failed valid message"); fi
if "$COMMIT_HOOK" "$tmp_bad" >/dev/null 2>&1; then notes+=("attribution: commit-msg hook failed to block invalid message"); else attribution=$((attribution+2)); fi
rm -f "$tmp_ok" "$tmp_bad"

# Repo audit pass
if "$AUDIT_SCRIPT" "$REPO" "upstream/main" >/dev/null 2>&1; then
  attribution=$((attribution+1))
else
  notes+=("attribution: audit script reported violation")
fi

overall=$(( (triage + verification + attribution) / 3 ))
status="PASS"
if (( triage < 8 || verification < 8 || attribution < 8 )); then
  status="FAIL"
fi

cat <<REPORT
## OpenClaw Maintainer Weekly Smoke

| Category | Score (0-10) | Status |
|---|---:|---|
| Triage quality | $triage | $( ((triage>=8)) && echo PASS || echo FAIL ) |
| Verification evidence | $verification | $( ((verification>=8)) && echo PASS || echo FAIL ) |
| Attribution compliance | $attribution | $( ((attribution>=8)) && echo PASS || echo FAIL ) |
| Overall | $overall | $status |

### Checks
- CLAUDE protocol coverage: $( ((triage>=8)) && echo strong || echo needs work )
- Verification gate coverage: $( ((verification>=8)) && echo strong || echo needs work )
- Hook and attribution guardrails: $( ((attribution>=8)) && echo strong || echo needs work )

### Notes
REPORT

if ((${#notes[@]}==0)); then
  echo "- No issues detected"
else
  for n in "${notes[@]}"; do
    echo "- $n"
  done
fi

if [[ "$status" != "PASS" ]]; then
  exit 1
fi
