import { existsSync } from "node:fs";
import path from "node:path";
import { createRequestHandler } from "react-router";

const mode = process.env.NODE_ENV ?? "production";
// @ts-expect-error build output is generated by `react-router build`.
const build = () => import("./build/server/index.js");
const handleRequest = createRequestHandler(build, mode);

const appDir = process.cwd();
const clientDir = path.join(appDir, "build", "client");

function resolveStaticAsset(pathname: string): string | null {
  if (pathname === "/" || pathname.endsWith("/")) {
    return null;
  }

  // Route requests without file extensions to SSR handlers.
  if (!pathname.includes(".")) {
    return null;
  }

  const normalizedPath = pathname.replace(/^\/+/, "");
  const resolved = path.resolve(clientDir, normalizedPath);

  const relativePath = path.relative(clientDir, resolved);
  if (relativePath.startsWith("..") || path.isAbsolute(relativePath)) {
    return null;
  }

  if (existsSync(resolved)) {
    return resolved;
  }

  return null;
}

const port = Number(process.env.PORT ?? "3000");

Bun.serve({
  port,
  async fetch(request: Request) {
    const url = new URL(request.url);
    const assetPath = resolveStaticAsset(url.pathname);

    if (assetPath) {
      return new Response(Bun.file(assetPath));
    }

    return handleRequest(request);
  },
});

console.log(`[scrybase] listening on http://localhost:${port}`);
