#!/usr/bin/env bash
set -euo pipefail

WS="/Users/sawyer/.openclaw/workspace-sentinel"
AGENTS_MD="$WS/AGENTS.md"
CLAUDE_MD="$WS/CLAUDE.md"
SOUL_MD="$WS/SOUL.md"
BOOTSTRAP_MD="$WS/BOOTSTRAP.md"
IDENTITY_MD="$WS/IDENTITY.md"
BUILD_MD="$WS/BUILD.md"
HOOK_DIR="$WS/hooks/git"
COMMIT_HOOK="$HOOK_DIR/commit-msg"
PREPUSH_HOOK="$HOOK_DIR/pre-push"
AUDIT_SCRIPT="$WS/scripts/agent-attribution-audit.sh"

has_text() {
  local pattern="$1" file="$2"
  LC_ALL=C grep -Eiq "$pattern" "$file"
}

contract=0
verification=0
attribution=0
notes=()

# --- CONTRACT INTEGRITY (10) ---
if has_text "## Mission" "$AGENTS_MD" && has_text "## Scope" "$AGENTS_MD"; then contract=$((contract+2)); else notes+=("contract: missing mission/scope in AGENTS"); fi
if has_text "## Severity Rubric" "$AGENTS_MD"; then contract=$((contract+2)); else notes+=("contract: missing severity rubric"); fi
if has_text "## False-Positive Control" "$AGENTS_MD"; then contract=$((contract+2)); else notes+=("contract: missing false-positive control"); fi
if has_text "## Reporting Contract" "$AGENTS_MD" && has_text "## Verification Gates" "$AGENTS_MD"; then contract=$((contract+2)); else notes+=("contract: weak reporting or verification sections"); fi
if cmp -s "$AGENTS_MD" "$CLAUDE_MD"; then contract=$((contract+2)); else notes+=("contract: AGENTS.md and CLAUDE.md drift detected"); fi

# --- VERIFICATION DISCIPLINE (10) ---
if has_text "Verification over confidence|prove claims with evidence" "$SOUL_MD"; then verification=$((verification+2)); else notes+=("verification: weak SOUL verification language"); fi
if has_text "trust boundaries|blast radius|verification plan" "$BOOTSTRAP_MD"; then verification=$((verification+2)); else notes+=("verification: bootstrap missing triage requirements"); fi
if has_text "BUILD\.md" "$BOOTSTRAP_MD" && [[ -f "$BUILD_MD" ]]; then verification=$((verification+2)); else notes+=("verification: BUILD ledger missing or bootstrap does not require it"); fi
if has_text "decision, evidence, risks/blockers, next action" "$BOOTSTRAP_MD" && has_text "Risks/Blockers" "$SOUL_MD"; then verification=$((verification+2)); else notes+=("verification: reporting shape drift detected"); fi
if has_text "Avoid security theater|evidence-backed|blast radius" "$IDENTITY_MD"; then verification=$((verification+2)); else notes+=("verification: identity anchor missing operator-signal language"); fi

# --- ATTRIBUTION COMPLIANCE (10) ---
if [[ -x "$COMMIT_HOOK" ]]; then attribution=$((attribution+1)); else notes+=("attribution: commit-msg hook missing/not executable"); fi
if [[ -x "$PREPUSH_HOOK" ]]; then attribution=$((attribution+1)); else notes+=("attribution: pre-push hook missing/not executable"); fi
if [[ -x "$AUDIT_SCRIPT" ]]; then attribution=$((attribution+1)); else notes+=("attribution: audit script missing/not executable"); fi
if has_text "No commit metadata may reference agent names, assistants, or AI terms" "$BOOTSTRAP_MD"; then attribution=$((attribution+1)); else notes+=("attribution: bootstrap policy missing"); fi

# Synthetic commit message tests
if [[ -x "$COMMIT_HOOK" ]]; then
  tmp_ok="$(mktemp)"
  tmp_bad="$(mktemp)"
  printf 'fix(contract): tighten sentinel reporting rules\n' > "$tmp_ok"
  printf 'fix: generated by Claude\n\nCo-Authored-By: Bot <bot@example.com>\n' > "$tmp_bad"

  if "$COMMIT_HOOK" "$tmp_ok" >/dev/null 2>&1; then attribution=$((attribution+3)); else notes+=("attribution: commit-msg hook failed valid message"); fi
  if "$COMMIT_HOOK" "$tmp_bad" >/dev/null 2>&1; then notes+=("attribution: commit-msg hook failed to block invalid message"); else attribution=$((attribution+3)); fi

  rm -f "$tmp_ok" "$tmp_bad"
else
  notes+=("attribution: synthetic commit message tests skipped because commit hook is not executable")
fi

overall=$(( (contract + verification + attribution) / 3 ))
status="PASS"
if (( contract < 8 || verification < 8 || attribution < 8 )); then
  status="FAIL"
fi

cat <<REPORT
## sentinel Weekly Specialist Smoke

| Category | Score (0-10) | Status |
|---|---:|---|
| Contract integrity | $contract | $( ((contract>=8)) && echo PASS || echo FAIL ) |
| Verification discipline | $verification | $( ((verification>=8)) && echo PASS || echo FAIL ) |
| Attribution compliance | $attribution | $( ((attribution>=8)) && echo PASS || echo FAIL ) |
| Overall | $overall | $status |

### Notes
REPORT

if ((${#notes[@]}==0)); then
  echo "- No issues detected"
else
  for n in "${notes[@]}"; do
    echo "- $n"
  done
fi

if [[ "$status" != "PASS" ]]; then
  exit 1
fi